version: '3'
services:
  app:
    container_name: sport
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${GO_PORT}:${GO_PORT}
    volumes:
      - ./cmd/api:/cmd/api
    depends_on:
      - db
    networks:
      - backend

  db:
    container_name: sports_db
    image: postgres:latest
    env_file:
      - .env
    environment:
      DATABASE_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - backend

networks:
  backend: